"""
Verification script for the production database schema.

Tests:
  1. init_db() creates all tables
  2. Users, Documents, QueryLog tables exist
  3. UUID primary keys are auto-generated by PostgreSQL
  4. doc_id column exists, is unique, indexed, and auto-generated
  5. Timestamps are auto-generated by PostgreSQL
  6. Foreign key relationships work correctly
  7. Cascade deletes propagate
  8. doc_id can be explicitly set (upload flow scenario)
  9. Cleanup — removes test data
"""

import sys
import os
import uuid

# Ensure project root is on sys.path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from sqlalchemy import inspect, text
from src.db.database import engine, SessionLocal, init_db
from src.db.models import User, Document, QueryLog


def main():
    print("=" * 60)
    print("PRODUCTION SCHEMA VERIFICATION")
    print("=" * 60)

    # ── 1. Initialize database ──
    print("\n[1/9] Running init_db()...")
    init_db()
    print("  OK  init_db() completed successfully")

    # ── 2. Verify tables exist ──
    print("\n[2/9] Checking tables...")
    inspector = inspect(engine)
    tables = inspector.get_table_names()
    expected = {"users", "documents", "query_logs"}
    for tbl in expected:
        if tbl in tables:
            print(f"  OK  Table '{tbl}' exists")
        else:
            print(f"  FAIL Table '{tbl}' MISSING")
            sys.exit(1)

    # ── 3. Verify columns ──
    print("\n[3/9] Checking columns...")
    for tbl in expected:
        cols = [c["name"] for c in inspector.get_columns(tbl)]
        print(f"  {tbl}: {cols}")

    # ── 4. Verify doc_id column on documents ──
    print("\n[4/9] Checking doc_id column on documents...")
    doc_cols = {c["name"]: c for c in inspector.get_columns("documents")}
    assert "doc_id" in doc_cols, "doc_id column MISSING from documents table"
    print(f"  OK  doc_id column exists, type={doc_cols['doc_id']['type']}")

    # Check unique constraint
    unique_constraints = inspector.get_unique_constraints("documents")
    indexes = inspector.get_indexes("documents")
    doc_id_indexed = any(
        "doc_id" in (idx.get("column_names", []) or [])
        for idx in indexes
    )
    doc_id_unique = any(
        "doc_id" in (uc.get("column_names", []) or [])
        for uc in unique_constraints
    ) or any(
        idx.get("unique", False) and "doc_id" in (idx.get("column_names", []) or [])
        for idx in indexes
    )
    print(f"  OK  doc_id indexed={doc_id_indexed}, unique={doc_id_unique}")

    # ── 5. Insert test User ──
    print("\n[5/9] Testing User insert (UUID + timestamp auto-gen)...")
    db = SessionLocal()
    try:
        user = User(
            email="test_verify_v2@example.com",
            hashed_password="fake_hashed_pw_for_testing",
            full_name="Schema Test User V2",
        )
        db.add(user)
        db.commit()
        db.refresh(user)
        assert user.id is not None, "User ID was not auto-generated"
        assert user.created_at is not None, "User created_at was not auto-generated"
        assert user.is_active is True, "User is_active default failed"
        print(f"  OK  User created: id={user.id}")

        # ── 6. Insert Document with auto-generated doc_id ──
        print("\n[6/9] Testing Document insert (auto-generated doc_id)...")
        doc_auto = Document(
            owner_id=user.id,
            filename="auto_docid_test.pdf",
            content_type="application/pdf",
            file_size_bytes=1000,
            chunk_count=5,
        )
        db.add(doc_auto)
        db.commit()
        db.refresh(doc_auto)
        assert doc_auto.id is not None, "Document.id was not auto-generated"
        assert doc_auto.doc_id is not None, "Document.doc_id was not auto-generated"
        assert doc_auto.id != doc_auto.doc_id, "id and doc_id should be different UUIDs"
        print(f"  OK  Document created: id={doc_auto.id}, doc_id={doc_auto.doc_id}")

        # ── 7. Insert Document with explicit doc_id (upload flow scenario) ──
        print("\n[7/9] Testing Document insert (explicit doc_id — upload flow)...")
        explicit_doc_id = uuid.uuid4()
        doc_explicit = Document(
            owner_id=user.id,
            doc_id=explicit_doc_id,
            filename="explicit_docid_test.pdf",
            content_type="application/pdf",
            file_size_bytes=2000,
            chunk_count=10,
        )
        db.add(doc_explicit)
        db.commit()
        db.refresh(doc_explicit)
        assert doc_explicit.doc_id == explicit_doc_id, (
            f"Explicit doc_id mismatch: expected {explicit_doc_id}, got {doc_explicit.doc_id}"
        )
        print(f"  OK  Document created with explicit doc_id={doc_explicit.doc_id}")

        # ── 8. Insert test QueryLog ──
        print("\n[8/9] Testing QueryLog + relationships...")
        qlog = QueryLog(
            user_id=user.id,
            document_id=doc_auto.id,
            question="What are the termination provisions?",
            answer="Test answer for schema verification.",
            chunks_retrieved=5,
            latency_ms=230,
        )
        db.add(qlog)
        db.commit()
        db.refresh(qlog)
        assert qlog.id is not None, "QueryLog ID was not auto-generated"
        print(f"  OK  QueryLog created: id={qlog.id}")

        # Verify relationships
        db.refresh(user)
        assert len(user.documents) == 2, "User.documents relationship broken"
        assert len(user.query_logs) == 1, "User.query_logs relationship broken"
        print(f"  OK  User.documents = {len(user.documents)} doc(s)")
        print(f"  OK  User.query_logs = {len(user.query_logs)} log(s)")

        # ── 9. Cleanup — cascade delete ──
        print("\n[9/9] Testing cascade delete (User -> Documents, QueryLogs)...")
        db.delete(user)
        db.commit()

        remaining_docs = db.query(Document).filter_by(id=doc_auto.id).count()
        remaining_docs2 = db.query(Document).filter_by(id=doc_explicit.id).count()
        remaining_logs = db.query(QueryLog).filter_by(id=qlog.id).count()
        assert remaining_docs == 0, "Cascade delete failed for auto doc"
        assert remaining_docs2 == 0, "Cascade delete failed for explicit doc"
        assert remaining_logs == 0, "Cascade delete failed for QueryLogs"
        print("  OK  Cascade delete verified -- all child records removed")

    except Exception as e:
        db.rollback()
        print(f"\n  FAIL: {e}")
        raise
    finally:
        db.close()

    print("\n" + "=" * 60)
    print("ALL CHECKS PASSED")
    print("=" * 60)


if __name__ == "__main__":
    main()
